development:
  host: "alex.mongohq.com"
  port: 10042
  database: "decisionmakr_devtest"
  username: decisionmakr
  password: devtest
  uri: <%= ENV['MONGODB_DEV_URI'] %>

test:
  uri: <%= ENV['MONGODB_DEV_URI'] %>

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGODB_URI'] %>
