development:
  host: "alex.mongohq.com"
  port: 10042
  database: "decisionmakr_devtest"
  username: decisionmakr
  password: devtest

production:
  host: "alex.mongohq.com"
  port: 10042
  database: "decisionmakr_devtest"
  username: decisionmakr
  password: devtest

# set these environment variables on your prod server
#production:
  #uri: <%= ENV['MONGODB_URI'] %>
